User: {
  shape: class
  label: "«abstract» User"
}

Renter: {
  shape: class
  label: "Renter"
}

Owner: {
  shape: class
  label: "Owner"
}

Admin: {
  shape: class
  label: "Admin"
}

Car: {
  shape: class
  label: "Car"
}

Reservation: {
  shape: class
  label: "Reservation\n(koppeltabel User-Car)"
}

Ride: {
  shape: class
  label: "Ride\n(koppeltabel User-Car)"
}

RidePhoto: {
  shape: class
  label: "RidePhoto\n(koppeltabel Reservation-Ride)"
}

BonusPoints: {
  shape: class
  label: "BonusPoints\n(koppeltabel User-Ride)"
}

Renter -> User: "inherits"
Owner -> User: "inherits"
Admin -> User: "inherits"

Owner -> Car: "*..1"

Car -> Reservation: "0..*"
Reservation -> Car: "1"

User -> Reservation: "0..*"
Reservation -> User: "1"

Reservation -> Ride: "0..*"
Ride -> Reservation: "1"

Ride -> RidePhoto: "1..*"
RidePhoto -> Ride: "1"

User -> BonusPoints: "0..*"
BonusPoints -> User: "1"

Ride -> BonusPoints: "0..*"