services:
  backend:
    build: ./backend          # Bouw lokaal vanuit ./backend
    env_file: .env.local      # Gebruik lokale env
    ports:
      - "8081:8080"
    volumes:
      - ./backend/photos:/app/photos
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8
    env_file: .env.local
    ports:
      - "3306:3306"           # Handig als je lokaal met DB wil verbinden
    volumes:
      - local_db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file: .env.local
    ports:
      - "8083:80"
    depends_on:
      - db

volumes:
  local_db_data:
