# docker-compose.prod.yml
services:
  backend:
    build: ./backend
    image: gielvangaal/fantastic-lamp-backend:prod
    env_file: .env.prod
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./backend/photos:/app/photos
      - ./.env:/app/.env

  db:
    image: mysql:8
    env_file: .env.prod
    volumes:
      - prod_db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file: .env.prod
    ports:
      - "8084:80"
    depends_on:
      - db

volumes:
  prod_db_data:
