### Register new user
POST http://localhost:8081/auth/users/register
Content-Type: application/json

{
  "emailAddress": "PeterJackson@hotmail.com",
  "firstName": "Peter",
  "lastName": "Jackson",
  "birthDate": "1998-01-05",
  "userType": "OWNER",
  "bankAccount": "ojghbjsk234820348",
  "bankAccountName": "HR P Jackson",
  "password": "Ditismijnwachtwoord"
}

> {%
    client.global.set("access_token", response.body.accessToken);
    client.global.set("user_id", response.body.user.id)
%}

### Log in to api and key jwt
POST http://localhost:8081/auth/users/login
Content-Type: application/json

{
  "emailAddress": "PeterJackson@hotmail.com",
  "password": "Ditismijnwachtwoord"
}
> {%
    client.global.set("access_token", response.body.accessToken);
    client.global.set("user_id", response.body.user.id)

%}

### Get all availabilities
GET http://localhost:8081/availabilities
Accept: application/json

### Get availability by ID
GET http://localhost:8081/availabilities/9d785f64-5717-4562-b3fc-2c963f66d004
Accept: application/json

### Get availability by carId
GET http://localhost:8081/availabilities/car/4b285f64-5717-4562-b3fc-2c963f66b001
Accept: application/json

### Get available availabilities
GET http://localhost:8081/availabilities/available
Accept: application/json

### Get available availabilities with timeslot filter
GET http://localhost:8081/availabilities/available?startDate=2025-10-01T06:00&endDate=2025-10-15T18:00
Accept: application/json

### Get available availabilities filterd by carId
GET http://localhost:8081/availabilities/available/car/4b285f64-5717-4562-b3fc-2c963f66b005
Accept: application/json

### Create a new availability
POST http://localhost:8081/availabilities
Content-Type: application/json
Accept: application/json

{
  "carId": "7f57db8e-9684-4257-92fe-5d942e4e8cd2",
  "startDate": "2025-10-22T08:00:00",
  "endDate": "2025-10-22T12:00:00"
}


### Update an existing availability
PUT http://localhost:8081/availabilities/9d785f64-5717-4562-b3fc-2c963f66d004
Content-Type: application/json
Accept: application/json

{
  "carId": "7f57db8e-9684-4257-92fe-5d942e4e8cd2",
  "startDate": "2025-10-23T09:00:00",
  "endDate": "2025-10-23T15:00:00"
}

### Delete an availability
DELETE http://localhost:8081/availabilities/9d785f64-5717-4562-b3fc-2c963f66d004
Accept: application/json
