@baseUrl = http://localhost:8081

### Log in
POST {{baseUrl}}/auth/users/login
Content-Type: application/json

{
  "emailAddress": "niels.verhoeven@outlook.com",
  "password": "hash12"
}
> {%
    client.global.set("access_token", response.body.accessToken);
    client.global.set("user_id", response.body.user.id);
%}

### Get my cars
GET {{baseUrl}}/cars/owned
Authorization: Bearer {{access_token}}
Accept: application/json

> {%
    client.global.set("car_id", response.body[0].id);
%}


### Get all availabilities
GET {{baseUrl}}/availabilities
Authorization: Bearer {{access_token}}
Accept: application/json

### Get availability by ID (uses stored id)
GET {{baseUrl}}/availabilities/{{availability_id}}
Authorization: Bearer {{access_token}}
Accept: application/json

### Get availability by carId
GET {{baseUrl}}/availabilities/car/{{car_id}}
Authorization: Bearer {{access_token}}
Accept: application/json

### Get available availabilities
GET {{baseUrl}}/availabilities/available
Authorization: Bearer {{access_token}}
Accept: application/json

### Get available availabilities with timeslot filter
GET {{baseUrl}}/availabilities/available?startDate=2025-10-01T06:00&endDate=2025-10-15T18:00
Authorization: Bearer {{access_token}}
Accept: application/json

### Get available availabilities filtered by carId
GET {{baseUrl}}/availabilities/available/car/{{car_id}}
Authorization: Bearer {{access_token}}
Accept: application/json

### Get all availabilities for a user
GET {{baseUrl}}/availabilities/owned
Authorization: Bearer {{access_token}}
Accept: application/json

### Create a new availability
POST {{baseUrl}}/availabilities
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

{
  "carId": "{{car_id}}",
  "startDate": "2025-10-22T08:00:00",
  "endDate": "2025-10-22T12:00:00"
}
> {%
    client.global.set("availability_id", response.body.id);
%}

### Update an existing availability
PUT {{baseUrl}}/availabilities/{{availability_id}}
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

{
  "carId": "{{car_id}}",
  "startDate": "2025-10-23T09:00:00",
  "endDate": "2025-10-23T15:00:00"
}

### Delete an availability
DELETE {{baseUrl}}/availabilities/{{availability_id}}
Authorization: Bearer {{access_token}}
Accept: application/json
