@baseUrl = https://fl-prod.gielvangaal.dev

### Register new user
POST {{baseUrl}}/auth/users/register
Content-Type: application/json

{
  "emailAddress": "PeterJackson1@hotmail.com",
  "firstName": "Peter",
  "lastName": "Jackson",
  "birthDate": "1998-01-05",
  "userType": "OWNER",
  "bankAccount": "ojghbjsk234820348",
  "bankAccountName": "HR P Jackson",
  "vehicleLocation": "0342309480",
  "password": "Ditismijnwachtwoord"
}

> {%
    client.global.set("access_token", response.body.accessToken);
    client.global.set("user_id", response.body.user.id)
%}



### Get all cars
GET {{baseUrl}}/cars
Accept: application/json
Authorization: Bearer {{access_token}}

### Get car by id
GET {{baseUrl}}/cars/id/1dcdc1b0-ccdf-436a-9c66-77acb5eb5a39
Accept: application/json
Authorization: Bearer {{access_token}}

### Get car locations
GET {{baseUrl}}/cars/location
Accept: application/json
Authorization: Bearer {{access_token}}


### Create a new car
POST {{baseUrl}}/cars
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "brand": "Toyota",
  "model": "Corolla",
  "buildYear": 2015,
  "transmissionType": "AUTOMATIC",
  "color": "WHITE",
  "fuelType": "ICE",
  "length": 1,
  "width": 1750,
  "seats": 2,
  "isofixCompatible": true,
  "phoneMount": true,
  "luggageSpace": 350.0,
  "parkingSensors": true,
  "locationX": 52.3702,
  "locationY": 4.8952,
  "licensePlate": "12-AB-CD",
  "pricePerDay": 65.0,
  "purchasePrice": 15000.0,
  "residualValue": 10000.0,
  "usageYears": 8,
  "annualKm": 12000,
  "energyCostPerKm": 0.08,
  "maintenanceCostPerKm": 0.04,
  "averageConsumption": 20
}

### Update a car
### For this test to work, you must be logged in, else ownerId is absent
PUT {{baseUrl}}/cars/id/4b285f64-5717-4562-b3fc-2c963f66b001
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "ownerId": "3fa85f64-5717-4562-b3fc-2c963f66a002",
  "brand": "Land Rover",
  "model": "Series 3",
  "buildYear": 1975,
  "transmissionType": "MANUAL",
  "color": "GREEN",
  "fuelType": "ICE",
  "length": 3880,
  "width": 1600,
  "seats": 12,
  "isofixCompatible": false,
  "phoneMount": false,
  "luggageSpace": 200.0,
  "parkingSensors": false,
  "locationX": 51.5652,
  "locationY": 3.5912,
  "licensePlate": "98-YA-67",
  "pricePerDay": 80.0,
  "purchasePrice": 25000.0,
  "residualValue": 15000.0,
  "usageYears": 5,
  "annualKm": 15000,
  "energyCostPerKm": 0.10,
  "maintenanceCostPerKm": 0.05,
  "averageConsumption": 20
}

### Optional: Get filtered cars
GET {{baseUrl}}/cars?phonemount=false&color=GREY&color=RED
Accept: application/json
Authorization: Bearer {{access_token}}

### Delete a car
DELETE {{baseUrl}}/cars/id/4b285f64-5717-4562-b3fc-2c963f66b001
Accept: application/json
Authorization: Bearer {{access_token}}

### Get TCO
GET {{baseUrl}}/cars/tco/1dcdc1b0-ccdf-436a-9c66-77acb5eb5a39
Accept: application/json
Authorization: Bearer {{access_token}}

### Get CPK
GET {{baseUrl}}/cars/cpk/1dcdc1b0-ccdf-436a-9c66-77acb5eb5a39
Accept: application/json
Authorization: Bearer {{access_token}}

### Get carlist
GET {{baseUrl}}/cars/carlist
Accept: application/json
Authorization: Bearer {{access_token}}


### Log in to api and key jwt
POST {{baseUrl}}/auth/users/login
Content-Type: application/json

{
  "emailAddress": "niels.verhoeven@outlook.com",
  "password": "hash12"
}
> {%
    client.global.set("access_token", response.body.accessToken);
    client.global.set("user_id", response.body.user.id)

%}

### Get owned cars
GET {{baseUrl}}/cars/owned
Accept: application/json
Authorization: Bearer {{access_token}}

