### Upload photos
POST http://localhost:8081/photos/cars/7f57db8e-9684-4257-92fe-5d942e4e8cd2
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="file"; filename="car_1.jpg"

< ./test-images/car_1.jpg
--boundary123
Content-Disposition: form-data; name="file"; filename="car_2.jpg"

< ./test-images/car_2.jpg
--boundary123--