@baseUrl = http://localhost:8081

### Register new user
POST {{baseUrl}}/auth/users/register
Content-Type: application/json

{
  "emailAddress": "PeteJackson@hotmail.com",
  "firstName": "Pete",
  "lastName": "Jackson",
  "birthDate": "1977-01-05",
  "userType": "OWNER",
  "bankAccount": "ojghbjsk234820348",
  "bankAccountName": "HR P Jackson",
  "password": "Ditismijnwachtwoord"
}

> {%
    client.global.set("access_token", response.body.accessToken);
    client.global.set("user_id", response.body.user.id)
%}

### Log in to api and key jwt
POST {{baseUrl}}/auth/users/login
Content-Type: application/json

{
  "emailAddress": "PeteJackson@hotmail.com",
  "password": "Ditismijnwachtwoord"
}
> {%
    client.global.set("access_token", response.body.accessToken);
    client.global.set("user_id", response.body.user.id)

%}

### Get all reservations
GET {{baseUrl}}/reservations
Authorization: Bearer {{access_token}}
Accept: application/json


### Get reservation by ID
GET {{baseUrl}}/reservations/ffb94c34-dada-487b-8700-8db2fe1d7c96
Authorization: Bearer {{access_token}}
Accept: application/json


### Get reservations by userId
GET {{baseUrl}}/reservations/user/8a6d3b58-a110-4f5e-91ed-d4e690be4358
Authorization: Bearer {{access_token}}
Accept: application/json


### Get reservations by carId
GET {{baseUrl}}/reservations/car/88de78dd-c3af-4c39-94a5-729305af26c3
Authorization: Bearer {{access_token}}
Accept: application/json


### Create a new reservation
POST {{baseUrl}}/reservations
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

{
  "userId": "ab92991c-6d83-4f65-8efd-c18c6af8d0df",
  "carId": "88de78dd-c3af-4c39-94a5-729305af26c3",
  "startDate": "2026-01-11T09:00:00",
  "endDate": "2026-01-14T12:00:00",
  "status": "UPCOMING"
}


### Update an existing reservation
PUT {{baseUrl}}/reservations/38ddcba3-1e06-4c3a-9da8-842ebe0167b1
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

{
  "userId": "ab92991c-6d83-4f65-8efd-c18c6af8d0df",
  "carId": "88de78dd-c3af-4c39-94a5-729305af26c3",
  "startDate": "2026-01-12T09:00:00",
  "endDate": "2026-01-14T12:00:00",
  "status": "UPCOMING"
}

### Delete a reservation
DELETE {{baseUrl}}/reservations/38ddcba3-1e06-4c3a-9da8-842ebe0167b1
Authorization: Bearer {{access_token}}
Accept: application/json

### Reservation list
GET {{baseUrl}}/reservations/user/reservationList/ab92991c-6d83-4f65-8efd-c18c6af8d0df
Authorization: Bearer {{access_token}}
Accept: application/json
