### Log in to api and key jwt
POST http://localhost:8080/auth/users/login
Content-Type: application/json

{
    "emailAddress":"ivarvisser@hotmail.com",
    "password":"Ditismijnwachtwoord"
}
> {%
    client.global.set("access_token", response.body.accessToken);
%}

### Register new user
POST http://localhost:8080/auth/users/register
Content-Type: application/json

{
"emailAddress": "ivarvisser@hotmail.com",
"firstName": "Ivar",
"lastName": "Visser",
"birthDate": "1998-12-05",
"userType": "OWNER",
"bankAccount": "ojghbjsk234820348",
"bankAccountName": "HR I Visser",
"vehicleLocation": "0342309480"
"password": "Ditismijnwachtwoord"
}

> {%
    client.global.set("access_token", response.body.accessToken);
%}

### Refresh cookcie
POST http://localhost:8080/refresh
#Save the access token in a variable

> {%
    client.global.set("access_token", response.body.accessToken);
%}

### Get all users
GET http://localhost:8080/users
Authorization: Bearer {{access_token}}