@baseUrl = http://localhost:8081

### Register new user
POST {{baseUrl}}/auth/users/register
Content-Type: application/json

{
  "emailAddress": "JohnJackson@hotmail.com",
  "firstName": "Peter",
  "lastName": "Jackson",
  "birthDate": "1998-01-05",
  "userType": "OWNER",
  "bankAccount": "ojghbjsk234820348",
  "bankAccountName": "HR P Jackson",
  "password": "Ditismijnwachtwoord"
}

> {%
    client.global.set("access_token", response.body.accessToken);
    client.global.set("user_id", response.body.user.id)
%}

### Log in to api and key jwt
POST {{baseUrl}}/auth/users/login
Content-Type: application/json

{
  "emailAddress": "JohnJackson@hotmail.com",
  "password": "Ditismijnwachtwoord"
}
> {%
    client.global.set("access_token", response.body.accessToken);
    client.global.set("user_id", response.body.user.id)

%}

### Refresh cookcie
POST {{baseUrl}}/refresh
#Save the access token in a variable

> {%
    client.global.set("access_token", response.body.accessToken);
%}

### Update acount item like name or password
PUT {{baseUrl}}/users/account/{{user_id}}/firstName
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "value": "Halloooo"
}

### Delete user account with its id
DELETE {{baseUrl}}/users/account/{{user_id}}
Authorization: Bearer {{access_token}}

