# Domeinklassen
User: {
  shape: class
  label: "«abstract» User"
}
Renter: {shape: class}
Owner: {shape: class}
Admin: {shape: class}

Car: {shape: class}
Reservation: {shape: class}
Ride: {shape: class}
Photo: {shape: class}
BonusPoints: {shape: class}

# Domein-erfenis
Renter -> User: "inherits"
Owner -> User: "inherits"
Admin -> User: "inherits"

# Repositories
BaseRepository: {shape: class}

CarRepository: {shape: class}
CarRepository -> BaseRepository: "inherits"
CarRepository -> Car: "manages"

ReservationRepository: {shape: class}
ReservationRepository -> BaseRepository: "inherits"
ReservationRepository -> Reservation: "manages"

UserRepository: {shape: class}
UserRepository -> BaseRepository: "inherits"
UserRepository -> User: "manages"

RideRepository: {shape: class}
RideRepository -> BaseRepository: "inherits"
RideRepository -> Ride: "manages"

PhotoRepository: {shape: class}
PhotoRepository -> BaseRepository: "inherits"
PhotoRepository -> Photo: "manages"

BonusPointsRepository: {shape: class}
BonusPointsRepository -> BaseRepository: "inherits"
BonusPointsRepository -> BonusPoints: "manages"

# Controllers / Endpoints
CarController: {shape: class}
CarController -> CarRepository: "uses"

ReservationController: {shape: class}
ReservationController -> ReservationRepository: "uses"

UserController: {shape: class}
UserController -> UserRepository: "uses"

RideController: {shape: class}
RideController -> RideRepository: "uses"

PhotoController: {shape: class}
PhotoController -> PhotoRepository: "uses"

BonusPointsController: {shape: class}
BonusPointsController -> BonusPointsRepository: "uses"
